# Generated by Django 4.0.5 on 2022-07-06 08:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.TextField(verbose_name='Роль')),
                ('age', models.IntegerField(verbose_name='Возвраст')),
                ('corp', models.CharField(max_length=254, verbose_name='Университет / Организация / Самостоятельно')),
                ('choice', models.CharField(choices=[('Разработка программы сервера на Django', 'Разработка программы сервера на Django'), ('Вёрстка сайтов по макетам (HTML + CSS)', 'Вёрстка сайтов по макетам (HTML + CSS)'), ('Разработка мобильного UI на React-native', 'Разработка мобильного UI на React-native'), ('Создание Web-дизайна', 'Создание Web-дизайна'), ('Разработка мобильного приложения на IOS', 'Разработка мобильного приложения на IOS'), ('Разработка мобильного приложения на Android', 'Разработка мобильного приложения на Android'), ('Разработка UI на одном из JavaScript фреймворке', 'Разработка UI на одном из JavaScript фреймворке'), ('Разработка приложений под Windows 10 на C++', 'Разработка приложений под Windows 10 на C++')], max_length=300, verbose_name='Выберите кейс')),
                ('flag', models.BooleanField(verbose_name='Принял ли пользовательское соглашение')),
            ],
            options={
                'verbose_name': 'Аккаунт участника',
                'verbose_name_plural': 'Аккаунты участников',
            },
        ),
        migrations.CreateModel(
            name='Case1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст 1 кейса',
            },
        ),
        migrations.CreateModel(
            name='Case2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст 2 кейса',
            },
        ),
        migrations.CreateModel(
            name='Case3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст 3 кейса',
            },
        ),
        migrations.CreateModel(
            name='Case4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст 4 кейса',
            },
        ),
        migrations.CreateModel(
            name='Case5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст 5 кейса',
            },
        ),
        migrations.CreateModel(
            name='Case6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст 6 кейса',
            },
        ),
        migrations.CreateModel(
            name='Case7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст 7 кейса',
            },
        ),
        migrations.CreateModel(
            name='Case8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст 8 кейса',
            },
        ),
        migrations.CreateModel(
            name='CasesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Страница кейсов',
            },
        ),
        migrations.CreateModel(
            name='ConceptText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Страница концепции',
            },
        ),
        migrations.CreateModel(
            name='DateText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Страница дат',
            },
        ),
        migrations.CreateModel(
            name='ImageCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to='static/src/images/cases')),
            ],
            options={
                'verbose_name': 'картинка',
                'verbose_name_plural': 'Картинки кейсов',
            },
        ),
        migrations.CreateModel(
            name='LastText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Кнопки и конечная информация',
            },
        ),
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Основная страница',
            },
        ),
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Страница вопросов',
            },
        ),
    ]
